# sqlite directory name for anonymous databases
# set empty, for creating database file in plugin's folder by default
sqlite-directory: "database"

# default mysql connection properties
mysql-properties: "sslMode=DISABLED&autoReconnect=true&useUnicode=true&serverTimezone=UTC"

# Hikari connection pool settings (https://github.com/brettwooldridge/HikariCP)
hikari:
  auto-commit: true
  connection-timeout: 30000
  idle-timeout: 600000
  keepalive-time: 0
  max-lifetime: 1800000
  maximum-pool-size: 10
