name: DataManager
main: me.hteppl.data.DataManager
version: "${pom.version}"
api: 1.0.13
load: STARTUP
authors:
  - "https://github.com/hteppl"
  - "https://github.com/IWareQ"
website: "https://github.com/hteppl/DataManager"